##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}


# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

# Media Apps floating
windowrule {
    name = media-defaults

    match:class = ^(imv|mpv|org\.pulseaudio\.pavucontrol)$
    
    float = yes
    center = yes
    size = monitor_w*0.7 monitor_h*0.7
}

windowrule {
    name = waybar-popups
    # Add more apps here if needed
    match:initial_class = ^(com\.app\.(btop|gazelle|bluetui))$
    float = true
    size = monitor_w*0.5 monitor_h*0.75
    center = true
}

windowrule {
    name = steam-popups
    match:initial_class = ^(steam)$
    match:initial_title = ^(Friends List|Steam Settings|Screenshot Uploader|Steam Guard|Chat|.* - Chat)$
    float = true
    size = monitor_w*0.5 monitor_h*0.75
    center = true
}

windowrule {
    name = steam-secondary
    match:initial_class = ^(steam)$
    match:initial_title = ^(?!Steam$).*$
    float = true
    size = monitor_w*0.5 monitor_h*0.75
    center = true
}

windowrule = match:class ^(steam_app|gamescope)$, fullscreen true
# windowrule = match:class ^(vesktop|vencord|discord|Spotify|firefox)$, float true
# windowrule = match:class ^(vesktop|vencord|discord|Spotify)$, size 1200 900