################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# name, resolution@refresh-rate, position, scale 
monitor = DP-1, 1920x1080@179.96, 0x0, 1
monitor = DP-2, 1920x1080@143.98, 1920x0, 1

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1

workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
